services:
    _defaults:
        public: true

    Imatic\Bundle\DataBundle\Data\Command\CommandExecutor:
        arguments:
            - '@Imatic\Bundle\DataBundle\Data\Command\HandlerRepository'
            - '%kernel.debug%'

    Imatic\Bundle\DataBundle\Data\Command\CommandExecutorInterface:
        alias: Imatic\Bundle\DataBundle\Data\Command\CommandExecutor

    Imatic\Bundle\DataBundle\Data\Command\HandlerRepository:
        arguments:
            - '@service_container'

    Imatic\Bundle\DataBundle\Data\Command\HandlerRepositoryInterface:
        alias: Imatic\Bundle\DataBundle\Data\Command\HandlerRepository

    Imatic\Bundle\DataBundle\Data\Driver\DriverRepository: ~

    Imatic\Bundle\DataBundle\Data\Driver\DriverRepositoryInterface:
        alias: Imatic\Bundle\DataBundle\Data\Driver\DriverRepository

    Imatic\Bundle\DataBundle\Data\Query\QueryExecutor:
        autowire: true

    Imatic\Bundle\DataBundle\Data\Query\QueryExecutorInterface:
        alias: Imatic\Bundle\DataBundle\Data\Query\QueryExecutor

    Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\PagerFactory: ~

    Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\DisplayCriteriaQueryBuilderDelegate:
        autowire: true

    Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\DisplayCriteriaQueryBuilderInterface:
        alias: Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\DisplayCriteriaQueryBuilderDelegate

    Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\FilterRuleProcessorDelegate: ~
