services:
    Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\DisplayCriteriaQueryBuilder:
        tags:
            - { name: imatic_data.display_criteria_query_builder }

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\FilterRuleProcessor\CallbackProcessor:
        public: false
        tags:
            - { name: imatic_data.filter_rule_processor, priority: 6 }

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\FilterRuleProcessor\RuleBooleanProcessor:
        public: false
        tags:
            - { name: imatic_data.filter_rule_processor, priority: 5 }

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\FilterRuleProcessor\BetweenOperatorProcessor:
        public: false
        tags:
            - { name: imatic_data.filter_rule_processor, priority: 4 }

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\FilterRuleProcessor\NotBetweenOperatorProcessor:
        public: false
        tags:
            - { name: imatic_data.filter_rule_processor, priority: 3 }

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\FilterRuleProcessor\ContainsOperatorProcessor:
        public: false
        tags:
            - { name: imatic_data.filter_rule_processor, priority: 2 }

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\FilterRuleProcessor\EmptyOperatorProcessor:
        public: false
        tags:
            - { name: imatic_data.filter_rule_processor, priority: 1 }

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\FilterRuleProcessor\InNotInOperatorProcessor:
        public: false
        tags:
            - { name: imatic_data.filter_rule_processor, priority: 1 }

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\FilterRuleProcessor\DefaultRuleProcessor:
        public: false
        tags:
            - { name: imatic_data.filter_rule_processor, priority: 0 }



    ### DEPRECATED ALIASES ###

    imatic_data.doctrine.display_criteria_query_builder:
        alias: Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\DisplayCriteriaQueryBuilder

    imatic_data.doctrine.callback_processor:
        alias: Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\FilterRuleProcessor\CallbackProcessor

    imatic_data.doctrine.rule_boolean_processor:
        alias: Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\FilterRuleProcessor\RuleBooleanProcessor

    imatic_data.doctrine.between_operator_processor:
        alias: Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\FilterRuleProcessor\BetweenOperatorProcessor

    imatic_data.doctrine.not_between_operator_processor:
        alias: Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\FilterRuleProcessor\NotBetweenOperatorProcessor

    imatic_data.doctrine.contains_operator_processor:
        alias: Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\FilterRuleProcessor\ContainsOperatorProcessor

    imatic_data.doctrine.empty_operator_processor:
        alias: Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\FilterRuleProcessor\EmptyOperatorProcessor

    imatic_data.doctrine.in_not_in_operator_processor:
        alias: Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\FilterRuleProcessor\InNotInOperatorProcessor

    imatic_data.doctrine.default_rule_processor:
        alias: Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\FilterRuleProcessor\DefaultRuleProcessor
