services:
    Imatic\Bundle\DataBundle\Data\Command\CommandExecutor:
        arguments:
            - '@Imatic\Bundle\DataBundle\Data\Command\ContainerHandlerRepository'
            - '%kernel.debug%'

    Imatic\Bundle\DataBundle\Data\Command\CommandExecutorInterface:
        alias: Imatic\Bundle\DataBundle\Data\Command\CommandExecutor

    Imatic\Bundle\DataBundle\Data\Command\HandlerRepository:
        public: false

    Imatic\Bundle\DataBundle\Data\Command\HandlerRepositoryInterface:
        alias: Imatic\Bundle\DataBundle\Data\Command\HandlerRepository

    Imatic\Bundle\DataBundle\Data\Command\ContainerHandlerRepository:
        autowire: true

    Imatic\Bundle\DataBundle\Data\Driver\DriverRepository: ~

    Imatic\Bundle\DataBundle\Data\Driver\DriverRepositoryInterface:
        alias: Imatic\Bundle\DataBundle\Data\Driver\DriverRepository

    Imatic\Bundle\DataBundle\Data\Query\QueryExecutor:
        autowire: true

    Imatic\Bundle\DataBundle\Data\Query\QueryExecutorInterface:
        alias: Imatic\Bundle\DataBundle\Data\Query\QueryExecutor

    Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\PagerFactory: ~

    Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\DisplayCriteriaQueryBuilderDelegate:
        autowire: true

    Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\DisplayCriteriaQueryBuilderInterface:
        alias: Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\DisplayCriteriaQueryBuilderDelegate

    Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\FilterRuleProcessorDelegate: ~

    ### DEPRECATED ALIASES ###

    imatic_data.command_executor:
        alias: Imatic\Bundle\DataBundle\Data\Command\CommandExecutor

    imatic_data.decorated_command_handler_repository:
        alias: Imatic\Bundle\DataBundle\Data\Command\HandlerRepository

    imatic_data.command_handler_repository:
        alias: Imatic\Bundle\DataBundle\Data\Command\ContainerHandlerRepository

    imatic_data.driver_repository:
        alias: Imatic\Bundle\DataBundle\Data\Driver\DriverRepository

    imatic_data.query_executor:
        alias: Imatic\Bundle\DataBundle\Data\Query\QueryExecutor

    imatic_data.pager_factory:
        alias: Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\PagerFactory

    imatic_data.display_criteria_query_builder:
        alias: Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\DisplayCriteriaQueryBuilderDelegate

    imatic_data.filter_rule_processor:
        alias: Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\FilterRuleProcessorDelegate
