services:
    _defaults:
        public: true

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\ObjectManager:
        arguments:
            - '@doctrine.orm.entity_manager'

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\QueryExecutor:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\DisplayCriteriaQueryBuilderDelegate'

    imatic_data.driver.doctrine_orm:
        class: Imatic\Bundle\DataBundle\Data\Driver\Driver
        arguments:
            - 'doctrine.orm'
            - '@Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\QueryExecutor'
            - 'Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\QueryObjectInterface'
            - '@Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\ObjectManager'
        tags:
            - { name: imatic_data.driver }

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\Command\EditHandler:
        arguments:
            - '@Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\ObjectManager'
        tags:
            - { name: imatic_data.handler }

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\Command\CreateHandler:
        arguments:
            - '@Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\ObjectManager'
        tags:
            - { name: imatic_data.handler }

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\Command\DeleteHandler:
        arguments:
            - '@Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\ObjectManager'
            - '@Imatic\Bundle\DataBundle\Data\Query\QueryExecutor'
        tags:
            - { name: imatic_data.handler }

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\Command\RecordIterator:
        arguments:
            - '@Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\QueryExecutor'
            - '@Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\ResultIteratorFactory'

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\ResultIteratorFactory:
        arguments:
            - '@Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\ArrayDisplayCriteriaFactory'
            - '@Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\FilterFactory'
            - '@Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\QueryExecutor'
            - '@doctrine.orm.entity_manager'
