services:
    imatic_data.doctrine.display_criteria_query_builder:
        class: Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\DisplayCriteriaQueryBuilder
        tags:
            - { name: imatic_data.display_criteria_query_builder }

    imatic_data.doctrine.callback_processor:
        class: Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\FilterRuleProcessor\CallbackProcessor
        public: false
        tags:
            - { name: imatic_data.filter_rule_processor, priority: 6 }

    imatic_data.doctrine.rule_boolean_processor:
        class: Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\FilterRuleProcessor\RuleBooleanProcessor
        public: false
        tags:
            - { name: imatic_data.filter_rule_processor, priority: 5 }

    imatic_data.doctrine.between_operator_processor:
        class: Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\FilterRuleProcessor\BetweenOperatorProcessor
        public: false
        tags:
            - { name: imatic_data.filter_rule_processor, priority: 4 }

    imatic_data.doctrine.not_between_operator_processor:
        class: Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\FilterRuleProcessor\NotBetweenOperatorProcessor
        public: false
        tags:
            - { name: imatic_data.filter_rule_processor, priority: 3 }

    imatic_data.doctrine.contains_operator_processor:
        class: Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\FilterRuleProcessor\ContainsOperatorProcessor
        public: false
        tags:
            - { name: imatic_data.filter_rule_processor, priority: 2 }

    imatic_data.doctrine.empty_operator_processor:
        class: Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\FilterRuleProcessor\EmptyOperatorProcessor
        public: false
        tags:
            - { name: imatic_data.filter_rule_processor, priority: 1 }

    imatic_data.doctrine.in_not_in_operator_processor:
        class: Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\FilterRuleProcessor\InNotInOperatorProcessor
        public: false
        tags:
            - { name: imatic_data.filter_rule_processor, priority: 1 }

    imatic_data.doctrine.default_rule_processor:
        class: Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\FilterRuleProcessor\DefaultRuleProcessor
        public: false
        tags:
            - { name: imatic_data.filter_rule_processor, priority: 0 }
