services:
    imatic_data.doctrine.dbal.query_executor:
        class: Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\QueryExecutor
        arguments:
            - @doctrine.dbal.default_connection
            - @imatic_data.doctrine.display_criteria_query_builder
            - @imatic_data.driver.doctrine_dbal.schema

    imatic_data.driver.doctrine_dbal.command.create:
        class: Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\Command\CreateHandler
        arguments:
            - @doctrine.dbal.default_connection
            - @imatic_data.driver.doctrine_dbal.schema
        tags:
            - { name: imatic_data.handler, alias: imatic_data.doctrine_dbal.generic_create }

    imatic_data.driver.doctrine_dbal.command.edit:
        class: Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\Command\EditHandler
        arguments:
            - @doctrine.dbal.default_connection
            - @imatic_data.driver.doctrine_dbal.schema
        tags:
            - { name: imatic_data.handler, alias: imatic_data.doctrine_dbal.generic_edit }

    imatic_data.driver.doctrine_dbal.command.create_or_edit:
        class: Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\Command\CreateOrEditHandler
        arguments:
            - @imatic_data.doctrine.dbal.query_executor
        tags:
            - { name: imatic_data.handler, alias: imatic_data.doctrine_dbal.generic_create_or_edit }

    imatic_data.driver.doctrine_dbal.command.delete:
        class: Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\Command\DeleteHandler
        arguments:
            - @doctrine.dbal.default_connection
        tags:
            - { name: imatic_data.handler, alias: imatic_data.doctrine_dbal.generic_delete }

    imatic_data.driver.doctrine_dbal.command.soft_delete:
        class: Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\Command\SoftDeleteHandler
        arguments:
            - @imatic_data.doctrine.dbal.query_executor
        tags:
            - { name: imatic_data.handler, alias: imatic_data.doctrine_dbal.generic_soft_delete }

    imatic_data.driver.doctrine_dbal.schema:
        class: Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\Schema\Schema
        arguments:
            - @doctrine.dbal.default_connection
        calls:
            - [overwriteColumnTypes, ["%imatic_data.driver.doctrine_dbal.schema.column_types%"]]

    imatic_data.driver.doctrine_dbal:
        class: Imatic\Bundle\DataBundle\Data\Driver\Driver
        arguments:
            - "doctrine.dbal"
            - @imatic_data.doctrine.dbal.query_executor
            - "Imatic\\Bundle\\DataBundle\\Data\\Driver\\DoctrineDBAL\\QueryObjectInterface"
        tags:
            - { name: imatic_data.driver }

    imatic_data.driver.doctrine_dbal.record_iterator:
        class: Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\Command\RecordIterator
        arguments:
            - @imatic_data.doctrine.dbal.query_executor
            - @imatic_data.driver.doctrine_dbal.result_iterator_factory

    imatic_data.driver.doctrine_dbal.result_iterator_factory:
        class: Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\ResultIteratorFactory
        arguments:
            - @imatic_data.array_display_criteria_factory
            - @imatic_data.filter_factory
            - @imatic_data.doctrine.dbal.query_executor
