services:
    _defaults:
        public: true

    imatic_data.doctrine.dbal.query_executor_delegate:
        class: Imatic\Bundle\DataBundle\Data\Query\QueryExecutorDelegate
        arguments:
            - '@Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\QueryExecutorFactory'

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\QueryExecutorFactory:
        autowire: true

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\QueryExecutor:
        factory: ['@Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\QueryExecutorFactory', createWithConnection]

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\Command\CreateHandler:
        arguments:
            - '@database_connection'
            - '@Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\Schema\Schema'
        tags:
            - { name: imatic_data.handler }

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\Command\EditHandler:
        arguments:
            - '@database_connection'
            - '@Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\Schema\Schema'
        tags:
            - { name: imatic_data.handler }

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\Command\CreateOrEditHandler:
        arguments:
            - '@Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\QueryExecutor'
        tags:
            - { name: imatic_data.handler }

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\Command\DeleteHandler:
        arguments:
            - '@database_connection'
        tags:
            - { name: imatic_data.handler }

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\Command\SoftDeleteHandler:
        arguments:
            - '@Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\QueryExecutor'
        tags:
            - { name: imatic_data.handler }

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\Schema\Schema:
        arguments:
            - '@database_connection'
        calls:
            - [overwriteColumnTypes, ["%imatic_data.driver.doctrine_dbal.schema.column_types%"]]

    imatic_data.driver.doctrine_dbal:
        class: Imatic\Bundle\DataBundle\Data\Driver\Driver
        arguments:
            - 'doctrine.dbal'
            - '@imatic_data.doctrine.dbal.query_executor_delegate'
            - 'Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\QueryObjectInterface'
        tags:
            - { name: imatic_data.driver }

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\Command\RecordIterator:
        arguments:
            - '@Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\QueryExecutor'
            - '@Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\ResultIteratorFactory'

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\ResultIteratorFactory:
        arguments:
            - '@Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\ArrayDisplayCriteriaFactory'
            - '@Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\FilterFactory'
            - '@Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\QueryExecutor'



    ### DEPRECATED ALIASES ###

    imatic_data.driver.doctrine_dbal.command.create:
        alias: Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\Command\CreateHandler

    imatic_data.doctrine.dbal.query_executor_factory:
        alias: Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\QueryExecutorFactory

    imatic_data.driver.doctrine_dbal.command.edit:
        alias: Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\Command\EditHandler

    imatic_data.driver.doctrine_dbal.command.create_or_edit:
        alias: Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\Command\CreateOrEditHandler

    imatic_data.driver.doctrine_dbal.command.delete:
        alias: Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\Command\DeleteHandler

    imatic_data.driver.doctrine_dbal.command.soft_delete:
        alias: Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\Command\SoftDeleteHandler

    imatic_data.driver.doctrine_dbal.schema:
        alias: Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\Schema\Schema

    imatic_data.driver.doctrine_dbal.record_iterator:
        alias: Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\Command\RecordIterator

    imatic_data.doctrine.dbal.query_executor:
        alias: Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\QueryExecutor

    imatic_data.driver.doctrine_dbal.result_iterator_factory:
        alias: Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\ResultIteratorFactory
