services:
    _defaults:
        public: true

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\ObjectManager:
        arguments:
            - '@doctrine.orm.entity_manager'

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\QueryExecutor:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\DisplayCriteriaQueryBuilderDelegate'

    imatic_data.driver.doctrine_orm:
        class: Imatic\Bundle\DataBundle\Data\Driver\Driver
        arguments:
            - 'doctrine.orm'
            - '@Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\QueryExecutor'
            - 'Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\QueryObjectInterface'
            - '@Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\ObjectManager'
        tags:
            - { name: imatic_data.driver }

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\Command\EditHandler:
        arguments:
            - '@Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\ObjectManager'
        tags:
            - { name: imatic_data.handler, alias: imatic_data.generic_edit }

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\Command\CreateHandler:
        arguments:
            - '@Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\ObjectManager'
        tags:
            - { name: imatic_data.handler, alias: imatic_data.generic_create }

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\Command\DeleteHandler:
        arguments:
            - '@Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\ObjectManager'
            - '@Imatic\Bundle\DataBundle\Data\Query\QueryExecutor'
        tags:
            - { name: imatic_data.handler, alias: imatic_data.generic_delete }

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\Command\RecordIterator:
        arguments:
            - '@Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\QueryExecutor'
            - '@Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\ResultIteratorFactory'

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\ResultIteratorFactory:
        arguments:
            - '@Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\ArrayDisplayCriteriaFactory'
            - '@Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\FilterFactory'
            - '@Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\QueryExecutor'
            - '@doctrine.orm.entity_manager'



    ### DEPRECATED ALIASES ###

    imatic_data.doctrine.object_manager:
        alias: Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\ObjectManager

    imatic_data.doctrine.query_executor:
        alias: Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\QueryExecutor

    imatic_data.driver.command.edit:
        alias: Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\Command\EditHandler

    imatic_data.driver.command.create:
        alias: Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\Command\CreateHandler

    imatic_data.driver.command.delete:
        alias: Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\Command\DeleteHandler

    imatic_data.driver.doctrine_orm.record_iterator:
        alias: Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\Command\RecordIterator

    imatic_data.driver.doctrine_orm.result_iterator_factory:
        alias: Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\ResultIteratorFactory
