services:
    # object manager
    imatic_data.doctrine.object_manager:
        class: Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\ObjectManager
        arguments:
            - @doctrine.orm.entity_manager

    # query executor
    imatic_data.doctrine.query_executor:
        class: Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\QueryExecutor
        arguments:
            - @doctrine.orm.entity_manager
            - @imatic_data.doctrine.display_criteria_query_builder

    # driver
    imatic_data.driver.doctrine_orm:
        class: Imatic\Bundle\DataBundle\Data\Driver\Driver
        arguments:
            - "doctrine.orm"
            - @imatic_data.doctrine.query_executor
            - "Imatic\\Bundle\\DataBundle\\Data\\Driver\\DoctrineORM\\QueryObjectInterface"
            - @imatic_data.doctrine.object_manager
        tags:
            - { name: imatic_data.driver }

    # Generic command handlers
    imatic_data.driver.command.edit:
        class: Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\Command\EditHandler
        arguments:
            - '@imatic_data.doctrine.object_manager'
        tags:
            - { name: imatic_data.handler, alias: imatic_data.generic_edit }

    imatic_data.driver.command.create:
        class: Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\Command\CreateHandler
        arguments:
            - '@imatic_data.doctrine.object_manager'
        tags:
            - { name: imatic_data.handler, alias: imatic_data.generic_create }

    imatic_data.driver.command.delete:
        class: Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\Command\DeleteHandler
        arguments:
            - '@imatic_data.doctrine.object_manager'
            - '@imatic_data.query_executor'
        tags:
            - { name: imatic_data.handler, alias: imatic_data.generic_delete }

    imatic_data.driver.doctrine_orm.record_iterator:
        class: Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\Command\RecordIterator
        arguments:
            - @imatic_data.doctrine.query_executor
            - @imatic_data.driver.doctrine_orm.result_iterator_factory

    imatic_data.driver.doctrine_orm.result_iterator_factory:
        class: Imatic\Bundle\DataBundle\Data\Driver\DoctrineORM\ResultIteratorFactory
        arguments:
            - @imatic_data.array_display_criteria_factory
            - @imatic_data.filter_factory
            - @imatic_data.doctrine.query_executor
            - @doctrine.orm.entity_manager
