services:
    imatic_data.doctrine.dbal.query_executor:
        class: Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\QueryExecutor
        arguments:
            - @doctrine.dbal.default_connection
            - @imatic_data.doctrine.display_criteria_query_builder
