services:
    imatic_data.doctrine.display_criteria_query_builder:
        class: Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\DisplayCriteriaQueryBuilder
        arguments:
            - @imatic_data.doctrine.rule_processor

    imatic_data.doctrine.rule_processor:
        class: Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\RuleProcessor\RuleProcessor
        calls:
            - [addRuleProcessor, [@imatic_data.doctrine.callback_processor]]
            - [addRuleProcessor, [@imatic_data.doctrine.rule_boolean_processor]]
            - [addRuleProcessor, [@imatic_data.doctrine.between_operator_processor]]
            - [addRuleProcessor, [@imatic_data.doctrine.not_between_operator_processor]]
            - [addRuleProcessor, [@imatic_data.doctrine.contains_operator_processor]]
            - [addRuleProcessor, [@imatic_data.doctrine.empty_operator_processor]]
            - [addRuleProcessor, [@imatic_data.doctrine.default_rule_processor]]

    imatic_data.doctrine.callback_processor:
        class: Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\RuleProcessor\CallbackProcessor

    imatic_data.doctrine.rule_boolean_processor:
        class: Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\RuleProcessor\RuleBooleanProcessor

    imatic_data.doctrine.default_rule_processor:
        class: Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\RuleProcessor\DefaultRuleProcessor

    imatic_data.doctrine.between_operator_processor:
        class: Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\RuleProcessor\BetweenOperatorProcessor

    imatic_data.doctrine.not_between_operator_processor:
        class: Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\RuleProcessor\NotBetweenOperatorProcessor

    imatic_data.doctrine.contains_operator_processor:
        class: Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\RuleProcessor\ContainsOperatorProcessor

    imatic_data.doctrine.empty_operator_processor:
        class: Imatic\Bundle\DataBundle\Data\Driver\DoctrineCommon\RuleProcessor\EmptyOperatorProcessor
