services:
    # command
    imatic_data.command_executor:
        class: Imatic\Bundle\DataBundle\Data\Command\CommandExecutor
        arguments:
            - '@imatic_data.command_handler_repository'
            - '%kernel.debug%'

    imatic_data.decorated_command_handler_repository:
        class: Imatic\Bundle\DataBundle\Data\Command\HandlerRepository
        public: false

    imatic_data.command_handler_repository:
        class: Imatic\Bundle\DataBundle\Data\Command\ContainerHandlerRepository
        arguments:
            - '@service_container'
            - '@imatic_data.decorated_command_handler_repository'

    # driver
    imatic_data.driver_repository:
        class: Imatic\Bundle\DataBundle\Data\Driver\DriverRepository

    # query executor
    imatic_data.query_executor:
        class: Imatic\Bundle\DataBundle\Data\Query\QueryExecutor
        arguments:
            - '@imatic_data.driver_repository'

    # display criteria
    imatic_data.pager_factory:
        class: Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\PagerFactory

    imatic_data.display_criteria_query_builder:
        class: Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\DisplayCriteriaQueryBuilderDelegate
        arguments:
            - '@imatic_data.filter_rule_processor'

    imatic_data.filter_rule_processor:
        class: Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\FilterRuleProcessorDelegate
