#todo zapisovat zavislosti s @ nebo bez
services:
    _defaults:
        public: true

    Imatic\Bundle\DataBundle\Data\Query\QueryExecutorDelegate:
        arguments:
            - '@Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\QueryExecutorFactory'

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\QueryExecutorFactory:
        autowire: true

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\QueryExecutor:
        factory: ['@Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\QueryExecutorFactory', createWithConnection]

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\Command\CreateHandler:
        arguments:
            - '@database_connection'
            - '@Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\Schema\Schema'
        tags:
            - { name: imatic_data.handler }

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\Command\EditHandler:
        arguments:
            - '@database_connection'
            - '@Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\Schema\Schema'
        tags:
            - { name: imatic_data.handler }

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\Command\CreateOrEditHandler:
        arguments:
            - '@Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\QueryExecutor'
        tags:
            - { name: imatic_data.handler }

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\Command\DeleteHandler:
        arguments:
            - '@database_connection'
        tags:
            - { name: imatic_data.handler }

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\Command\SoftDeleteHandler:
        arguments:
            - '@Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\QueryExecutor'
        tags:
            - { name: imatic_data.handler }

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\Schema\Schema:
        arguments:
            - '@database_connection'
        calls:
            - [overwriteColumnTypes, ["%imatic_data.driver.doctrine_dbal.schema.column_types%"]]

    imatic_data.driver.doctrine_dbal:
        class: Imatic\Bundle\DataBundle\Data\Driver\Driver
        arguments:
            - 'doctrine.dbal'
            - '@Imatic\Bundle\DataBundle\Data\Query\QueryExecutorDelegate'
            - 'Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\QueryObjectInterface'
        tags:
            - { name: imatic_data.driver }

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\Command\RecordIterator:
        arguments:
            - '@Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\QueryExecutor'
            - '@Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\ResultIteratorFactory'

    Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\ResultIteratorFactory:
        arguments:
            - '@Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\ArrayDisplayCriteriaFactory'
            - '@Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\FilterFactory'
            - '@Imatic\Bundle\DataBundle\Data\Driver\DoctrineDBAL\QueryExecutor'
