imports:
    - { resource: data.yml }

services:
    imatic_data.display_criteria.request_query_reader:
        class: Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\Reader\RequestQueryReader
        arguments:
            - @request_stack

    # Display criteria
    imatic_data.display_criteria_factory:
        class: Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\DisplayCriteriaFactory
        arguments:
            - @imatic_data.pager_factory
            - @form.factory
            - @imatic_data.display_criteria.request_query_reader

    # Form extensions
    imatic_data.form.extension.query_object:
        class: Imatic\Bundle\DataBundle\Form\Extension\EntityTypeQueryObjectExtension
        arguments:
            - '@imatic_data.query_executor'
        tags:
            - { name: 'form.type_extension', alias: entity }

    imatic_data.filter_factory:
        class: Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\FilterFactory
        arguments:
            - @service_container
