imports:
    - { resource: data.yml }

services:
    _defaults:
        public: true

    Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\Reader\RequestQueryReader:
        autowire: true

    Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\Reader\ExtJsReader:
        autowire: true

    Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\DisplayCriteriaFactory:
        autowire: true

    Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\ArrayDisplayCriteriaFactory:
        autowire: true

    Imatic\Bundle\DataBundle\Form\Extension\EntityTypeQueryObjectExtension:
        tags:
            - { name: 'form.type_extension', extended_type: Symfony\Bridge\Doctrine\Form\Type\EntityType }

    Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\FilterFactory:
        autowire: true

    Imatic\Bundle\DataBundle\Form\Type\Filter\ArrayRuleType:
        tags:
            - { name: form.type }
