imports:
    - { resource: data.yml }

services:
    # Display criteria
    imatic_data.display_criteria_factory:
        class: Imatic\Bundle\DataBundle\Request\Query\DisplayCriteriaFactory
        arguments:
            - @request_stack
            - @imatic_data.pager_factory
            - @form.factory

    imatic_data.array_display_criteria_factory:
        class: Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\ArrayDisplayCriteriaFactory
        arguments:
            - @imatic_data.pager_factory
            - @form.factory

    # Form extensions
    imatic_data.form.extension.query_object:
        class: Imatic\Bundle\DataBundle\Form\Extension\EntityTypeQueryObjectExtension
        arguments:
            - '@imatic_data.query_executor'
        tags:
            - { name: 'form.type_extension', alias: entity }

    imatic_data.filter_factory:
        class: Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\FilterFactory
        arguments:
            - @service_container
