imports:
    - { resource: data.yml }

services:
    imatic_data.request_query_display_criteria_reader:
        class: Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\Reader\RequestQueryReader
        arguments:
            - '@request_stack'

    imatic_data.extjs_display_criteria_reader:
        class: Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\Reader\ExtJsReader
        arguments:
            - '@request_stack'

    # Display criteria
    imatic_data.display_criteria_factory:
        class: Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\DisplayCriteriaFactory
        arguments:
            - '@imatic_data.pager_factory'
            - '@form.factory'
            - '@imatic_data.display_criteria_reader'

    imatic_data.array_display_criteria_factory:
        class: Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\ArrayDisplayCriteriaFactory
        arguments:
            - '@imatic_data.pager_factory'
            - '@form.factory'

    # Form extensions
    imatic_data.form.extension.query_object:
        class: Imatic\Bundle\DataBundle\Form\Extension\EntityTypeQueryObjectExtension
        arguments:
            - '@imatic_data.query_executor'
        tags:
            - { name: 'form.type_extension', extended_type: Symfony\Bridge\Doctrine\Form\Type\EntityType }

    imatic_data.filter_factory:
        class: Imatic\Bundle\DataBundle\Data\Query\DisplayCriteria\FilterFactory
        arguments:
            - '@service_container'

    imatic_data.array_rule_type:
        class: Imatic\Bundle\DataBundle\Form\Type\Filter\ArrayRuleType
        tags:
            - { name: form.type, alias: imatic_array_rule }
