services:
    imatic_data.command_executor:
        class: Imatic\Bundle\DataBundle\Data\Command\CommandExecutor
        arguments:
            - @imatic_data.handler_repository

    imatic_data.handler_repository:
        class: Imatic\Bundle\DataBundle\Data\Command\HandlerRepository

    imatic_data.object_manager:
        class: Imatic\Bundle\DataBundle\Data\Driver\Doctrine\ORM\ObjectManager
        arguments:
            - @doctrine.orm.entity_manager

    imatic_data.query_executor:
        class: Imatic\Bundle\DataBundle\Data\Driver\Doctrine\ORM\QueryExecutor
        arguments:
            - @doctrine.orm.entity_manager
