imports:
    - { resource: data.yml }

services:
    # Display criteria
    imatic_data.display_criteria_factory:
        class: Imatic\Bundle\DataBundle\Request\Query\DisplayCriteriaFactory
        arguments:
            - @request_stack
            - @imatic_data.pager_factory
            - @form.factory

    # Form filter
    imatic_data.form.type.filter:
        class: Imatic\Bundle\DataBundle\Form\Type\Filter\TextRuleType
        tags:
            - { name: form.type, alias: imatic_data_text_filter }
