imports:
    - { resource: data.yml }

services:
    # Display criteria
    imatic_data.display_criteria_factory:
        class: Imatic\Bundle\DataBundle\Request\Query\DisplayCriteriaFactory
        arguments:
            - @request_stack
            - @imatic_data.pager_factory
            - @form.factory

    # Form filter
