language: php

php: 7.4.0

addons:
    apt:
        packages:
            - graphviz

services:
    - postgresql

before_script:
    - phpenv config-rm xdebug.ini
    - composer install

script:
    - make test
