image: php:7.1

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - make configure-pipelines
          - make update-test
          - make test
        services:
          - db

definitions:
  services:
    db:
      image: postgres:9.4
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: data_bundle_test
